# content_normalizer.py
# Cleans up HTML generated by OpenAI

import re

def normalize_html(html: str) -> str:
    """Clean and normalize HTML from AI output."""

    if not html:
        return ""

    out = html

    # Remove markdown artifacts if any
    out = out.replace("```html", "").replace("```", "")

    # Remove double spaces
    out = re.sub(r"\s{2,}", " ", out)

    # Ensure paragraphs are wrapped correctly
    out = re.sub(r"\n+", "\n", out)

    # Ensure <p> formatting
    out = re.sub(r"(?i)<p>\s*", "<p>", out)
    out = re.sub(r"\s*</p>", "</p>", out)

    # Remove empty <p></p>
    out = re.sub(r"<p>\s*</p>", "", out)

    # Ensure spacing after headings
    out = re.sub(r"(</h2>|</h3>)(\S)", r"\1\n\n\2", out)

    # Ensure list formatting spacing
    out = re.sub(r"(</li>)(\S)", r"\1\n\2", out)

    # Strip leading/trailing whitespace
    out = out.strip()

    return out
